name: Lab CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BUILD_TYPE: Release

jobs:
  build-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        # Для генерации пакетов
        sudo apt-get install -y rpm
        
    - name: Create build directory
      run: mkdir -p build
    
    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ github.sha }}
    
    - name: Configure project
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
    
    - name: Build project
      working-directory: build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}
    
    - name: Generate packages
      working-directory: build
      run: |
        cpack -G "TGZ;DEB;RPM"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          build/*.tar.gz
          build/*.deb
          build/*.rpm
