name: CPack

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure project
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cmake -B build -DCPACK_PACKAGE_VERSION=$VERSION

      - name: Build and create packages
        run: |
          cd build
          cmake --build . --target package
          cpack -G "DEB;TGZ"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Ключевое исправление
        with:
          name: packages
          path: |
            build/*.deb
            build/*.tar.gz

  create-release:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4  # Также обновлено
        with:
          name: packages
          path: release-artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            release-artifacts/*.deb
            release-artifacts/*.tar.gz
