name: CPack Release

on:
  push:
    tags:
      - 'v*.*.*'  # Запускать при создании тегов, соответствующих шаблону v*.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Обязательно для CPack

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/_build -D PRINT_VERSION=1.0.0 ${{github.workspace}}

      - name: Build
        run: cmake --build ${{github.workspace}}/_build --config Release

      - name: Package with CPack
        run: cpack -C Release --config Release -B ${{github.workspace}}/_build

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}  # from release event
          asset_path: ${{ github.workspace }}/_build/*.deb
          asset_name: solver_${github.ref_name}.deb
          asset_content_type: application/vnd.debian.binary-package
