name: CPack

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]

jobs:
  build-and-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up environment
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y cmake build-essential rpm
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install wixtoolset -y  # Установка WiX
          fi

      - name: Configure project
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cmake -B build -DCPACK_PACKAGE_VERSION=$VERSION

      - name: Build and create packages
        run: |
          cd build
          cmake --build .
          if [ "$RUNNER_OS" == "Linux" ]; then
            cpack -G "DEB;TGZ;RPM"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cpack -G "WIX"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cpack -G "DragNDrop"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: |
            build/*.deb
            build/*.tar.gz
            build/*.rpm
            build/*.msi
            build/*.dmg

  create-release:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages-ubuntu-latest
          path: release-artifacts/linux
      - uses: actions/download-artifact@v4
        with:
          name: packages-windows-latest
          path: release-artifacts/windows
      - uses: actions/download-artifact@v4
        with:
          name: packages-macos-latest
          path: release-artifacts/macos

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            release-artifacts/linux/*.deb
            release-artifacts/linux/*.tar.gz
            release-artifacts/linux/*.rpm
            release-artifacts/windows/*.msi
            release-artifacts/macos/*.dmg
